  ⚙️ Chore:
    - '.github/*'
    - '.tools/*'

  🃏 Demos:
     - ./apps/demos/*

  { } State:
     - libs/state/*
     - libs/state/**/*

  </> Template:
     - libs/template/*
     - libs/template/**/*

  📖 Docs API:
    - libs/**/docs/**/*

  📚 Docs Web:
    - docs/*
    - docs/**/*

  🔬 Experimental:
    - libs/**/experimental/*
    - libs/**/experimental/**/*

  🛂 Test:
     - libs/**/spec/*
     - libs/**/spec/**/*
     - libs/**/perf/*
     - libs/**/perf/**/*
