# Add 'demo' label to any app file changes
  demo:
     - ./apps/*

# Add 'state' label to any change within the 'state' package
  state:
     - libs/state/*
     - libs/state/**/*

# Add 'template' label to any change within the 'template' package
  template:
     - libs/template/*
     - libs/template/**/*


# Add 'test' label to any change to *.spec.js files within the source dir
  test:
     - libs/**/*.spec.js
