version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: 'Install'
                command: npm install --frozen-lockfile --non-interactive
            - run: npm run nx affected:lint -- --base=origin/master --head=origin/${CIRCLE_BRANCH}
            - run: npm run nx affected:build -- --base=origin/master --head=origin/${CIRCLE_BRANCH}
            - run: npm run ng test -- --project=state --code-coverage
            - run: npm run ng test -- --project=template --code-coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test
