name: release

on:
  push:
    branches:
      - master

jobs:
  build-docs:

    runs-on: ubuntu-latest
    if: github.repository == 'BioPhoton/rx-angular'
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch --no-tags --prune --depth=5 origin master
      - run: npm install --frozen-lockfile --non-interactive

      - name: BuildDocs
        env:
      - run: npm run build-docs
