# TODO: https://github.com/actions/create-release/issues/64#issuecomment-638695206

name: Create State Release

on:
  push:
  # Sequence of patterns matched against refs/tags
  tags:
  - 'state@*' # Push events to matching state@*, i.e. state@1.0, state@20.15.10


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changelog.md
          draft: false
          prerelease: false
